### ISSUE TITLE
提示代理网络错误

### ISSUE THREAD

**Issue by citrusjunoss** [guzhongren/algolia-docsearch-upload-action#1]
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/18432488/190346683-0c6feab3-dc44-4de0-9d80-c960fe405918.png">

**Comment by guzhongren** [comment]
Hey, @citrusjunoss 
原来的Node CLI 已经很长时间不维护了，现在转向了algolia的CLI， 但是也有问题，等他们修复，我会发布2.1.0版就ok了

**Comment by citrusjunoss** [comment]
> Hey, @citrusjunoss 原来的Node CLI 已经很长时间不维护了，现在转向了algolia的CLI， 但是也有问题，等他们修复，我会发布2.1.0版就ok了

ok

**Comment by guzhongren** [comment]
Hey, @citrusjunoss Fixed, PLZ use v2.1.0

**Comment by citrusjunoss** [comment]
> Hey, @citrusjunoss Fixed, PLZ use v2.1.0

我试一下
